### ISSUE TITLE
CopyToDestination

### ISSUE THREAD

**Issue by bindaladitya001** [scaleracademy/dev-demo-day-submissions#4]
**Before you start, please follow this format for your issue title**:
PROJECT NAME - CopyToDestination

## ℹ️ Project information

1. **Repository Link:** _Provide us the link to your code. - https://github.com/bindaladitya001/CopyToDestination

2. **Short Project Description:** _One line crisp description of your project_ - Copying Data From One Location To the Another Location

3. **Demo Link:** _Demo Video with (if any, this might contain a website/ mobile application link, etc.)_

**Comment by bindaladitya001** [comment]
This is the project to transfer files or directories from one location to another

**Comment by YeswanthRajakumar** [comment]
#### Repository Link:  https://github.com/YeswanthRajakumar/Online_Hackathon_Hoster-HackView-

#### Project Description: 
* For Hosting virtual Hackathons and evaluating submissions
* Companies can host hackathons and give problem statements
* Individuals or team can Participate and submit their solutions to the problem
* Solutions will be reviewed by the resppective reviewers and result will be published for the specific teams

Demo Link: http://hackview.herokuapp.com/
